#include <sru21569.h>
#include "common.h"
#include "DRV_ASRC.h"

uint32_t DRV_ASRC_Init(void)
{
	*pREG_ASRC1_MUTE = (0<<BITP_ASRC_MUTE_MUTE0) | (0<<BITP_ASRC_MUTE_MUTE1) | (0<<BITP_ASRC_MUTE_MUTE2) | (0<<BITP_ASRC_MUTE_MUTE3);
	*pREG_ASRC1_CTL01 = (1<<BITP_ASRC_CTL01_EN0) | (0<<BITP_ASRC_CTL01_LENOUT0) | (1<<BITP_ASRC_CTL01_SMODEOUT0) | (1<<BITP_ASRC_CTL01_SMODEIN0) | (0<<BITP_ASRC_CTL01_AUTOMUTE0);

	return PASSED;
}

