#include "common.h"
#include "DRV_SPORT.h"

/* TDM16 for A2B Slave RX */
static void initSPORT0A(void)
{
	*pREG_SPORT0_CS0_A = 0x0000FFFF;
	*pREG_SPORT0_CS1_A = 0x00000000;
	*pREG_SPORT0_CS2_A = 0x00000000;
	*pREG_SPORT0_CS3_A = 0x00000000;

	*pREG_SPORT0_CTL_A = ENUM_SPORT_CTL_RX | ENUM_SPORT_CTL_SECONDARY_DIS | ENUM_SPORT_CTL_GCLK_DIS
						| ENUM_SPORT_CTL_EDGE_FS | ENUM_SPORT_CTL_RJUST_DIS | ENUM_SPORT_CTL_EARLY_FS | ENUM_SPORT_CTL_FS_LO /*ENUM_SPORT_CTL_FS_LO is actually HI*/
						| ENUM_SPORT_CTL_DATA_DEP_FS| ENUM_SPORT_CTL_EXTERNAL_FS | ENUM_SPORT_CTL_FS_REQ | ENUM_SPORT_CTL_CLK_FALL_EDGE /*ENUM_SPORT_CTL_CLK_RISE_EDGE*/
						| ENUM_SPORT_CTL_SERIAL_MC_MODE | ENUM_SPORT_CTL_EXTERNAL_CLK | ENUM_SPORT_CTL_PACK_DIS
						| ((32-1)<<BITP_SPORT_CTL_SLEN) | ENUM_SPORT_CTL_MSB_FIRST;
	*pREG_SPORT0_CTL2_A = ENUM_SPORT_CTL2_CLK_MUX_DIS | ENUM_SPORT_CTL2_FS_MUX_DIS;
	*pREG_SPORT0_MCTL_A = (0<<BITP_SPORT_MCTL_WOFFSET) | ((16-1)<<BITP_SPORT_MCTL_WSIZE) | (1<<BITP_SPORT_MCTL_MFD) | ENUM_SPORT_MCTL_MCPD_EN;
}

/* TDM16 for A2B Slave TX */
static void initSPORT0B(void)
{
	*pREG_SPORT0_CS0_B = 0x0000FFFF;
	*pREG_SPORT0_CS1_B = 0x00000000;
	*pREG_SPORT0_CS2_B = 0x00000000;
	*pREG_SPORT0_CS3_B = 0x00000000;

	*pREG_SPORT0_CTL_B = ENUM_SPORT_CTL_TX | ENUM_SPORT_CTL_SECONDARY_DIS | ENUM_SPORT_CTL_GCLK_DIS
						| ENUM_SPORT_CTL_EDGE_FS | ENUM_SPORT_CTL_RJUST_DIS | ENUM_SPORT_CTL_EARLY_FS | ENUM_SPORT_CTL_FS_LO /*ENUM_SPORT_CTL_FS_LO is actually HI*/
						| ENUM_SPORT_CTL_DATA_DEP_FS| ENUM_SPORT_CTL_EXTERNAL_FS | ENUM_SPORT_CTL_FS_REQ | ENUM_SPORT_CTL_CLK_FALL_EDGE /*ENUM_SPORT_CTL_CLK_RISE_EDGE*/
						| ENUM_SPORT_CTL_SERIAL_MC_MODE | ENUM_SPORT_CTL_EXTERNAL_CLK | ENUM_SPORT_CTL_PACK_DIS
						| ((32-1)<<BITP_SPORT_CTL_SLEN) | ENUM_SPORT_CTL_MSB_FIRST;
	*pREG_SPORT0_CTL2_B = ENUM_SPORT_CTL2_CLK_MUX_DIS | ENUM_SPORT_CTL2_FS_MUX_DIS;
	*pREG_SPORT0_MCTL_B = (0<<BITP_SPORT_MCTL_WOFFSET) | ((16-1)<<BITP_SPORT_MCTL_WSIZE) | (1<<BITP_SPORT_MCTL_MFD) | ENUM_SPORT_MCTL_MCPD_EN;
}

/* TDM16 for A2B ACC1 DRX0 */
static void initSPORT2A(void)
{
	*pREG_SPORT2_CS0_A = 0x0000FFFF;
	*pREG_SPORT2_CS1_A = 0x00000000;
	*pREG_SPORT2_CS2_A = 0x00000000;
	*pREG_SPORT2_CS3_A = 0x00000000;

	*pREG_SPORT2_CTL_A = ENUM_SPORT_CTL_RX | ENUM_SPORT_CTL_SECONDARY_DIS | ENUM_SPORT_CTL_GCLK_DIS
						| ENUM_SPORT_CTL_EDGE_FS | ENUM_SPORT_CTL_RJUST_DIS | ENUM_SPORT_CTL_EARLY_FS | ENUM_SPORT_CTL_FS_LO
						| ENUM_SPORT_CTL_DATA_DEP_FS| ENUM_SPORT_CTL_EXTERNAL_FS | ENUM_SPORT_CTL_FS_REQ | ENUM_SPORT_CTL_CLK_FALL_EDGE
						| ENUM_SPORT_CTL_SERIAL_MC_MODE | ENUM_SPORT_CTL_EXTERNAL_CLK | ENUM_SPORT_CTL_PACK_DIS
						| ((32-1)<<BITP_SPORT_CTL_SLEN) | ENUM_SPORT_CTL_MSB_FIRST;
	*pREG_SPORT2_CTL2_A = ENUM_SPORT_CTL2_CLK_MUX_DIS | ENUM_SPORT_CTL2_FS_MUX_DIS;
	*pREG_SPORT2_MCTL_A = (0<<BITP_SPORT_MCTL_WOFFSET) | ((16-1)<<BITP_SPORT_MCTL_WSIZE) | (1<<BITP_SPORT_MCTL_MFD) | ENUM_SPORT_MCTL_MCPD_EN;
}

/* TDM16 for A2B ACC2 DRX1 */
static void initSPORT2B(void)
{
	*pREG_SPORT2_CS0_B = 0x0000000F;
	*pREG_SPORT2_CS1_B = 0x00000000;
	*pREG_SPORT2_CS2_B = 0x00000000;
	*pREG_SPORT2_CS3_B = 0x00000000;

	*pREG_SPORT2_CTL_B = ENUM_SPORT_CTL_RX | ENUM_SPORT_CTL_SECONDARY_DIS | ENUM_SPORT_CTL_GCLK_DIS
						| ENUM_SPORT_CTL_EDGE_FS | ENUM_SPORT_CTL_RJUST_DIS | ENUM_SPORT_CTL_EARLY_FS | ENUM_SPORT_CTL_FS_LO
						| ENUM_SPORT_CTL_DATA_DEP_FS| ENUM_SPORT_CTL_EXTERNAL_FS | ENUM_SPORT_CTL_FS_REQ | ENUM_SPORT_CTL_CLK_FALL_EDGE
						| ENUM_SPORT_CTL_SERIAL_MC_MODE | ENUM_SPORT_CTL_EXTERNAL_CLK | ENUM_SPORT_CTL_PACK_DIS
						| ((32-1)<<BITP_SPORT_CTL_SLEN) | ENUM_SPORT_CTL_MSB_FIRST;
	*pREG_SPORT2_CTL2_B = ENUM_SPORT_CTL2_CLK_MUX_DIS | ENUM_SPORT_CTL2_FS_MUX_DIS;
	*pREG_SPORT2_MCTL_B = (0<<BITP_SPORT_MCTL_WOFFSET) | ((16-1)<<BITP_SPORT_MCTL_WSIZE) | (1<<BITP_SPORT_MCTL_MFD) | ENUM_SPORT_MCTL_MCPD_EN;
}

/* TDM16 for A2B PMIC DRX0 */
static void initSPORT3A(void)
{
	*pREG_SPORT3_CS0_A = 0x000000FF;
	*pREG_SPORT3_CS1_A = 0x00000000;
	*pREG_SPORT3_CS2_A = 0x00000000;
	*pREG_SPORT3_CS3_A = 0x00000000;

	*pREG_SPORT3_CTL_A = ENUM_SPORT_CTL_RX | ENUM_SPORT_CTL_SECONDARY_DIS | ENUM_SPORT_CTL_GCLK_DIS
						| ENUM_SPORT_CTL_EDGE_FS | ENUM_SPORT_CTL_RJUST_DIS | ENUM_SPORT_CTL_EARLY_FS | ENUM_SPORT_CTL_FS_LO
						| ENUM_SPORT_CTL_DATA_DEP_FS| ENUM_SPORT_CTL_EXTERNAL_FS | ENUM_SPORT_CTL_FS_REQ | ENUM_SPORT_CTL_CLK_FALL_EDGE
						| ENUM_SPORT_CTL_SERIAL_MC_MODE | ENUM_SPORT_CTL_EXTERNAL_CLK | ENUM_SPORT_CTL_PACK_DIS
						| ((32-1)<<BITP_SPORT_CTL_SLEN) | ENUM_SPORT_CTL_MSB_FIRST;
	*pREG_SPORT3_CTL2_A = ENUM_SPORT_CTL2_CLK_MUX_DIS | ENUM_SPORT_CTL2_FS_MUX_DIS;
	*pREG_SPORT3_MCTL_A = (0<<BITP_SPORT_MCTL_WOFFSET) | ((16-1)<<BITP_SPORT_MCTL_WSIZE) | (1<<BITP_SPORT_MCTL_MFD) | ENUM_SPORT_MCTL_MCPD_EN;
}

/* TDM16 for DSP2 TX Primary*/
static void initSPORT4A(void)
{
	*pREG_SPORT4_CS0_A = 0x0000FFFF;
	*pREG_SPORT4_CS1_A = 0x00000000;
	*pREG_SPORT4_CS2_A = 0x00000000;
	*pREG_SPORT4_CS3_A = 0x00000000;

	*pREG_SPORT4_CTL_A = ENUM_SPORT_CTL_TX | ENUM_SPORT_CTL_SECONDARY_DIS | ENUM_SPORT_CTL_GCLK_DIS
						| ENUM_SPORT_CTL_EDGE_FS | ENUM_SPORT_CTL_RJUST_DIS | ENUM_SPORT_CTL_EARLY_FS | ENUM_SPORT_CTL_FS_LO
						| ENUM_SPORT_CTL_DATA_DEP_FS| ENUM_SPORT_CTL_EXTERNAL_FS | ENUM_SPORT_CTL_FS_REQ | ENUM_SPORT_CTL_CLK_FALL_EDGE
						| ENUM_SPORT_CTL_SERIAL_MC_MODE | ENUM_SPORT_CTL_EXTERNAL_CLK | ENUM_SPORT_CTL_PACK_DIS
						| ((32-1)<<BITP_SPORT_CTL_SLEN) | ENUM_SPORT_CTL_MSB_FIRST;
	*pREG_SPORT4_CTL2_A = ENUM_SPORT_CTL2_CLK_MUX_DIS | ENUM_SPORT_CTL2_FS_MUX_DIS;
	*pREG_SPORT4_MCTL_A = (0<<BITP_SPORT_MCTL_WOFFSET) | ((16-1)<<BITP_SPORT_MCTL_WSIZE) | (1<<BITP_SPORT_MCTL_MFD) | ENUM_SPORT_MCTL_MCPD_EN;
}

/* TDM16 for DSP2 RX Primary*/
static void initSPORT4B(void)
{
	*pREG_SPORT4_CS0_B = 0x0000FFFF;
	*pREG_SPORT4_CS1_B = 0x00000000;
	*pREG_SPORT4_CS2_B = 0x00000000;
	*pREG_SPORT4_CS3_B = 0x00000000;

	*pREG_SPORT4_CTL_B = ENUM_SPORT_CTL_RX | ENUM_SPORT_CTL_SECONDARY_DIS | ENUM_SPORT_CTL_GCLK_DIS
						| ENUM_SPORT_CTL_EDGE_FS | ENUM_SPORT_CTL_RJUST_DIS | ENUM_SPORT_CTL_EARLY_FS | ENUM_SPORT_CTL_FS_LO
						| ENUM_SPORT_CTL_DATA_DEP_FS| ENUM_SPORT_CTL_EXTERNAL_FS | ENUM_SPORT_CTL_FS_REQ | ENUM_SPORT_CTL_CLK_FALL_EDGE
						| ENUM_SPORT_CTL_SERIAL_MC_MODE | ENUM_SPORT_CTL_EXTERNAL_CLK | ENUM_SPORT_CTL_PACK_DIS
						| ((32-1)<<BITP_SPORT_CTL_SLEN) | ENUM_SPORT_CTL_MSB_FIRST;
	*pREG_SPORT4_CTL2_B = ENUM_SPORT_CTL2_CLK_MUX_DIS | ENUM_SPORT_CTL2_FS_MUX_DIS;
	*pREG_SPORT4_MCTL_B = (0<<BITP_SPORT_MCTL_WOFFSET) | ((16-1)<<BITP_SPORT_MCTL_WSIZE) | (1<<BITP_SPORT_MCTL_MFD) | ENUM_SPORT_MCTL_MCPD_EN;
}

/* I2S for DSP TX Camping Scenario */
static void initSPORT6B(void)
{
	*pREG_SPORT6_CTL_B = ENUM_SPORT_CTL_TX | ENUM_SPORT_CTL_SECONDARY_DIS | ENUM_SPORT_CTL_GCLK_EN
						| ENUM_SPORT_CTL_EDGE_FS | ENUM_SPORT_CTL_RJUST_DIS | ENUM_SPORT_CTL_EARLY_FS | ENUM_SPORT_CTL_FS_HI
						| ENUM_SPORT_CTL_DATA_DEP_FS| ENUM_SPORT_CTL_EXTERNAL_FS | ENUM_SPORT_CTL_FS_REQ | ENUM_SPORT_CTL_CLK_RISE_EDGE
						| ENUM_SPORT_CTL_A_CTL_I2S_MODE | ENUM_SPORT_CTL_EXTERNAL_CLK | ENUM_SPORT_CTL_PACK_DIS
						| ((32-1)<<BITP_SPORT_CTL_SLEN) | ENUM_SPORT_CTL_MSB_FIRST;
	*pREG_SPORT6_CTL2_B = ENUM_SPORT_CTL2_CLK_MUX_DIS | ENUM_SPORT_CTL2_FS_MUX_DIS;

	*pREG_SPORT6_MCTL_B = 0x00;
}

/* I2S for VESS TX Power IC */
static void initSPORT7A(void)
{
	*pREG_SPORT7_CTL_A = ENUM_SPORT_CTL_TX | ENUM_SPORT_CTL_SECONDARY_DIS | ENUM_SPORT_CTL_GCLK_EN
						| ENUM_SPORT_CTL_EDGE_FS | ENUM_SPORT_CTL_RJUST_DIS | ENUM_SPORT_CTL_EARLY_FS | ENUM_SPORT_CTL_FS_HI
						| ENUM_SPORT_CTL_DATA_DEP_FS| ENUM_SPORT_CTL_EXTERNAL_FS | ENUM_SPORT_CTL_FS_REQ | ENUM_SPORT_CTL_CLK_RISE_EDGE
						| ENUM_SPORT_CTL_A_CTL_I2S_MODE | ENUM_SPORT_CTL_EXTERNAL_CLK | ENUM_SPORT_CTL_PACK_DIS
						| ((32-1)<<BITP_SPORT_CTL_SLEN) | ENUM_SPORT_CTL_MSB_FIRST;
	*pREG_SPORT7_CTL2_A = ENUM_SPORT_CTL2_CLK_MUX_DIS | ENUM_SPORT_CTL2_FS_MUX_DIS;

	*pREG_SPORT7_MCTL_A = 0x00;
}

/* I2S for ASRC RX Camping Scenario */
static void initSPORT7B(void)
{
	*pREG_SPORT7_CTL_B = ENUM_SPORT_CTL_RX | ENUM_SPORT_CTL_SECONDARY_DIS | ENUM_SPORT_CTL_GCLK_EN
						| ENUM_SPORT_CTL_EDGE_FS | ENUM_SPORT_CTL_RJUST_DIS | ENUM_SPORT_CTL_EARLY_FS | ENUM_SPORT_CTL_FS_HI
						| ENUM_SPORT_CTL_DATA_DEP_FS| ENUM_SPORT_CTL_EXTERNAL_FS | ENUM_SPORT_CTL_FS_REQ | ENUM_SPORT_CTL_CLK_RISE_EDGE
						| ENUM_SPORT_CTL_A_CTL_I2S_MODE | ENUM_SPORT_CTL_EXTERNAL_CLK | ENUM_SPORT_CTL_PACK_DIS
						| ((32-1)<<BITP_SPORT_CTL_SLEN) | ENUM_SPORT_CTL_MSB_FIRST;
	*pREG_SPORT7_CTL2_B = ENUM_SPORT_CTL2_CLK_MUX_DIS | ENUM_SPORT_CTL2_FS_MUX_DIS;

	*pREG_SPORT7_MCTL_B = 0x00;
}

static void enableSPORT(void)
{
#if (USE_DSP_CFG == 0u)	/* Output to AMP */
	*pREG_SPORT0_MCTL_A |= ENUM_SPORT_MCTL_EN;	/* MultiChannel Control Regiser - Rx from AMP */
	*pREG_SPORT0_MCTL_B |= ENUM_SPORT_MCTL_EN;	/* MultiChannel Control Regiser - Tx to AMP */
	*pREG_SPORT2_MCTL_A |= ENUM_SPORT_MCTL_EN;	/* MultiChannel Control Regiser - Rx from A2B#3(PMIC) */
	*pREG_SPORT3_MCTL_A |= ENUM_SPORT_MCTL_EN;	/* MultiChannel Control Regiser - Rx from A2B#4(ACC) */

	*pREG_DAI0_GBL_SP_EN =    (1<<BITP_DAI_GBL_SP_EN_GBL_SP0A_PC_EN)
							| (1<<BITP_DAI_GBL_SP_EN_GBL_SP0B_PC_EN)
							| (0<<BITP_DAI_GBL_SP_EN_GBL_SP1A_PC_EN)
							| (0<<BITP_DAI_GBL_SP_EN_GBL_SP1B_PC_EN)
							| (1<<BITP_DAI_GBL_SP_EN_GBL_SP2A_PC_EN)
							| (0<<BITP_DAI_GBL_SP_EN_GBL_SP2B_PC_EN)
							| (1<<BITP_DAI_GBL_SP_EN_GBL_SP3A_PC_EN)
							| (0<<BITP_DAI_GBL_SP_EN_GBL_SP3B_PC_EN)
							| (1<<BITP_DAI_GBL_SP_EN_GBL_SPEN_GRP0) | (1<<BITP_DAI_GBL_SP_EN_GBL_SPEN_GRP1)
							| (1<<BITP_DAI_GBL_SP_EN_GBL_SPEN_DAIX);

	*pREG_DAI1_GBL_SP_EN =    (0<<BITP_DAI_GBL_SP_EN_GBL_SP0A_PC_EN)
							| (0<<BITP_DAI_GBL_SP_EN_GBL_SP0B_PC_EN)
							| (0<<BITP_DAI_GBL_SP_EN_GBL_SP1A_PC_EN)
							| (0<<BITP_DAI_GBL_SP_EN_GBL_SP1B_PC_EN)
							| (0<<BITP_DAI_GBL_SP_EN_GBL_SP2A_PC_EN)
							| (1<<BITP_DAI_GBL_SP_EN_GBL_SP2B_PC_EN)
							| (1<<BITP_DAI_GBL_SP_EN_GBL_SP3A_PC_EN)
							| (1<<BITP_DAI_GBL_SP_EN_GBL_SP3B_PC_EN)
							| (0<<BITP_DAI_GBL_SP_EN_GBL_SPEN_GRP0) | (1<<BITP_DAI_GBL_SP_EN_GBL_SPEN_GRP1)
							| (1<<BITP_DAI_GBL_SP_EN_GBL_SPEN_DAIX);

	*pREG_DAI1_GBL_SP_EN |= (1<<BITP_DAI_GBL_SP_EN_GBL_SP_EN);
	*pREG_DAI0_GBL_SP_EN |= (1<<BITP_DAI_GBL_SP_EN_GBL_SP_EN);

	*pREG_DAI0_GBL_INT_EN =   (1<<BITP_DAI_GBL_INT_EN_GRP0_INT_EN)		| (1<<BITP_DAI_GBL_INT_EN_GRP1_INT_EN)
							| (1<<BITP_DAI_GBL_INT_EN_GRP0_SP0AINT_EN)
							| (1<<BITP_DAI_GBL_INT_EN_GRP0_SP0BINT_EN)
							| (0<<BITP_DAI_GBL_INT_EN_GRP0_SP1AINT_EN)
							| (0<<BITP_DAI_GBL_INT_EN_GRP0_SP1BINT_EN)
							| (1<<BITP_DAI_GBL_INT_EN_GRP1_SP2AINT_EN)
							| (0<<BITP_DAI_GBL_INT_EN_GRP1_SP2BINT_EN)
							| (1<<BITP_DAI_GBL_INT_EN_GRP1_SP3AINT_EN)
							| (0<<BITP_DAI_GBL_INT_EN_GRP1_SP3BINT_EN);

	*pREG_DAI1_GBL_INT_EN =   (0<<BITP_DAI_GBL_INT_EN_GRP0_INT_EN)		| (1<<BITP_DAI_GBL_INT_EN_GRP1_INT_EN)
							| (0<<BITP_DAI_GBL_INT_EN_GRP0_SP0AINT_EN)
							| (0<<BITP_DAI_GBL_INT_EN_GRP0_SP0BINT_EN)
							| (0<<BITP_DAI_GBL_INT_EN_GRP0_SP1AINT_EN)
							| (0<<BITP_DAI_GBL_INT_EN_GRP0_SP1BINT_EN)
							| (0<<BITP_DAI_GBL_INT_EN_GRP1_SP2AINT_EN)
							| (1<<BITP_DAI_GBL_INT_EN_GRP1_SP2BINT_EN)
							| (1<<BITP_DAI_GBL_INT_EN_GRP1_SP3AINT_EN)
							| (1<<BITP_DAI_GBL_INT_EN_GRP1_SP3BINT_EN);
#elif (USE_DSP_CFG == 1u)	/* Output to DSP2 */
	*pREG_SPORT0_MCTL_A |= ENUM_SPORT_MCTL_EN;	/* MultiChannel Control Regiser - Input from AMP */
	*pREG_SPORT2_MCTL_A |= ENUM_SPORT_MCTL_EN;	/* MultiChannel Control Regiser - Input from A2B#3(PMIC) */
	*pREG_SPORT3_MCTL_A |= ENUM_SPORT_MCTL_EN;	/* MultiChannel Control Regiser - Input from A2B#4(ACC) */

	*pREG_SPORT4_MCTL_A |= ENUM_SPORT_MCTL_EN;	/* MultiChannel Control Regiser - Outputput to DSP2 */

	*pREG_DAI0_GBL_SP_EN =    (1<<BITP_DAI_GBL_SP_EN_GBL_SP0A_PC_EN)
							| (0<<BITP_DAI_GBL_SP_EN_GBL_SP0B_PC_EN)
							| (0<<BITP_DAI_GBL_SP_EN_GBL_SP1A_PC_EN)
							| (0<<BITP_DAI_GBL_SP_EN_GBL_SP1B_PC_EN)
							| (1<<BITP_DAI_GBL_SP_EN_GBL_SP2A_PC_EN)
							| (0<<BITP_DAI_GBL_SP_EN_GBL_SP2B_PC_EN)
							| (1<<BITP_DAI_GBL_SP_EN_GBL_SP3A_PC_EN)
							| (0<<BITP_DAI_GBL_SP_EN_GBL_SP3B_PC_EN)
							| (1<<BITP_DAI_GBL_SP_EN_GBL_SPEN_GRP0) | (1<<BITP_DAI_GBL_SP_EN_GBL_SPEN_GRP1)
							| (1<<BITP_DAI_GBL_SP_EN_GBL_SPEN_DAIX);

	*pREG_DAI1_GBL_SP_EN =    (1<<BITP_DAI_GBL_SP_EN_GBL_SP0A_PC_EN)
							| (0<<BITP_DAI_GBL_SP_EN_GBL_SP0B_PC_EN)
							| (0<<BITP_DAI_GBL_SP_EN_GBL_SP1A_PC_EN)
							| (0<<BITP_DAI_GBL_SP_EN_GBL_SP1B_PC_EN)
							| (0<<BITP_DAI_GBL_SP_EN_GBL_SP2A_PC_EN)
							| (1<<BITP_DAI_GBL_SP_EN_GBL_SP2B_PC_EN)
							| (1<<BITP_DAI_GBL_SP_EN_GBL_SP3A_PC_EN)
							| (1<<BITP_DAI_GBL_SP_EN_GBL_SP3B_PC_EN)
							| (1<<BITP_DAI_GBL_SP_EN_GBL_SPEN_GRP0) | (1<<BITP_DAI_GBL_SP_EN_GBL_SPEN_GRP1)
							| (1<<BITP_DAI_GBL_SP_EN_GBL_SPEN_DAIX);

	*pREG_DAI1_GBL_SP_EN |= (1<<BITP_DAI_GBL_SP_EN_GBL_SP_EN);
	*pREG_DAI0_GBL_SP_EN |= (1<<BITP_DAI_GBL_SP_EN_GBL_SP_EN);

	*pREG_DAI0_GBL_INT_EN =   (1<<BITP_DAI_GBL_INT_EN_GRP0_INT_EN)		| (1<<BITP_DAI_GBL_INT_EN_GRP1_INT_EN)
							| (1<<BITP_DAI_GBL_INT_EN_GRP0_SP0AINT_EN)
							| (0<<BITP_DAI_GBL_INT_EN_GRP0_SP0BINT_EN)
							| (0<<BITP_DAI_GBL_INT_EN_GRP0_SP1AINT_EN)
							| (0<<BITP_DAI_GBL_INT_EN_GRP0_SP1BINT_EN)
							| (1<<BITP_DAI_GBL_INT_EN_GRP1_SP2AINT_EN)
							| (0<<BITP_DAI_GBL_INT_EN_GRP1_SP2BINT_EN)
							| (1<<BITP_DAI_GBL_INT_EN_GRP1_SP3AINT_EN)
							| (0<<BITP_DAI_GBL_INT_EN_GRP1_SP3BINT_EN);

	*pREG_DAI1_GBL_INT_EN =   (1<<BITP_DAI_GBL_INT_EN_GRP0_INT_EN)		| (1<<BITP_DAI_GBL_INT_EN_GRP1_INT_EN)
							| (1<<BITP_DAI_GBL_INT_EN_GRP0_SP0AINT_EN)
							| (0<<BITP_DAI_GBL_INT_EN_GRP0_SP0BINT_EN)
							| (0<<BITP_DAI_GBL_INT_EN_GRP0_SP1AINT_EN)
							| (0<<BITP_DAI_GBL_INT_EN_GRP0_SP1BINT_EN)
							| (0<<BITP_DAI_GBL_INT_EN_GRP1_SP2AINT_EN)
							| (1<<BITP_DAI_GBL_INT_EN_GRP1_SP2BINT_EN)
							| (1<<BITP_DAI_GBL_INT_EN_GRP1_SP3AINT_EN)
							| (1<<BITP_DAI_GBL_INT_EN_GRP1_SP3BINT_EN);
#endif
}

uint32_t DRV_SPORT_Init(void)
{
	
	initSPORT0A();
	initSPORT2A();
	initSPORT3A();
	initSPORT6B();
	initSPORT7A();
	initSPORT7B();
#if (USE_DSP_CFG == 0u)
	initSPORT0B();			/* Tx to AMP via A2B#1 */
#elif (USE_DSP_CFG == 1u)
	initSPORT4A();			/* TX to DSP2 for ANCASD */
#endif

	enableSPORT();

 return PASSED;
}

