/*****************************************************************************
 * SYSTEM_SPU.h
 *****************************************************************************/

#ifndef __SYSTEM_SPU_H__
#define __SYSTEM_SPU_H__


#define D_SYS_SPU_WP_SPORT0A			15
#define D_SYS_SPU_WP_SPORT0B			16
#define D_SYS_SPU_WP_SPORT1A			17
#define D_SYS_SPU_WP_SPORT1B			18
#define D_SYS_SPU_WP_SPORT2A			19
#define D_SYS_SPU_WP_SPORT2B			20
#define D_SYS_SPU_WP_SPORT3A			21
#define D_SYS_SPU_WP_SPORT3B			22
#define D_SYS_SPU_WP_SPORT4A			23
#define D_SYS_SPU_WP_SPORT4B			24
#define D_SYS_SPU_WP_SPORT5A			25
#define D_SYS_SPU_WP_SPORT5B			26
#define D_SYS_SPU_WP_SPORT6A			27
#define D_SYS_SPU_WP_SPORT6B			28
#define D_SYS_SPU_WP_SPORT7A			29
#define D_SYS_SPU_WP_SPORT7B			30
#define D_SYS_SPU_WP_UART0				31
#define D_SYS_SPU_WP_PORTA				34
#define D_SYS_SPU_WP_PORTB				35
#define D_SYS_SPU_WP_PORTC				36
#define D_SYS_SPU_WP_PORTD				37
#define D_SYS_SPU_WP_PORTE				38
#define D_SYS_SPU_WP_PADS				41
#define D_SYS_SPU_WP_PINT0				42
#define D_SYS_SPU_WP_PINT1				43
#define D_SYS_SPU_WP_PINT2				44
#define D_SYS_SPU_WP_PINT3				45
#define D_SYS_SPU_WP_PINT4				46
#define D_SYS_SPU_WP_WDG0				50
#define D_SYS_SPU_WP_SPORT0A_DMA0		66
#define D_SYS_SPU_WP_SPORT0B_DMA1		67
#define D_SYS_SPU_WP_SPORT1A_DMA2		68
#define D_SYS_SPU_WP_SPORT1B_DMA3		69
#define D_SYS_SPU_WP_SPORT2A_DMA4		70
#define D_SYS_SPU_WP_SPORT2B_DMA5		71
#define D_SYS_SPU_WP_SPORT3A_DMA6		72
#define D_SYS_SPU_WP_SPORT3B_DMA7		73
#define D_SYS_SPU_WP_SPORT4A_DMA10		74
#define D_SYS_SPU_WP_SPORT4B_DMA11		75
#define D_SYS_SPU_WP_SPORT5A_DMA12		76
#define D_SYS_SPU_WP_SPORT5B_DMA13		77
#define D_SYS_SPU_WP_SPORT6A_DMA14		78
#define D_SYS_SPU_WP_SPORT6B_DMA15		79
#define D_SYS_SPU_WP_SPORT7A_DMA16		80
#define D_SYS_SPU_WP_SPORT7B_DMA17		81
#define D_SYS_SPU_WP_UART0_RX_DMA20		82
#define D_SYS_SPU_WP_UART0_TX_DMA21		83
#define D_SYS_SPU_WP_MDMA0_SRC_DMA8		88
#define D_SYS_SPU_WP_MDMA0_DST_DMA9		89
#define D_SYS_SPU_WP_MDMA1_SRC_DMA18	90
#define D_SYS_SPU_WP_MDMA1_DST_DMA19	91
#define D_SYS_SPU_WP_SPI0				97
#define D_SYS_SPU_WP_SPI1				98
#define D_SYS_SPU_WP_SPI2				99
#define D_SYS_SPU_WP_SPI0_TX_DMA22		101
#define D_SYS_SPU_WP_SPI0_RX_DMA23		102
#define D_SYS_SPU_WP_SPI1_TX_DMA24		103
#define D_SYS_SPU_WP_SPI1_RX_DMA25		104
#define D_SYS_SPU_WP_SPI2_TX_DMA26		105
#define D_SYS_SPU_WP_SPI2_RX_DMA27		106
#define D_SYS_SPU_WP_MDMA2				140
#define D_SYS_SPU_WP_MDMA3				141


typedef enum _E_SYS_SPU_PID_
{
	E_SYS_SPU_PID_SPORT0A				= 0,				/* D_SYS_SPU_WP_SPORT0A */
	E_SYS_SPU_PID_SPORT0B,									/* D_SYS_SPU_WP_SPORT0B */
	E_SYS_SPU_PID_SPORT1A,									/* D_SYS_SPU_WP_SPORT1A */
	E_SYS_SPU_PID_SPORT4A,									/* D_SYS_SPU_WP_SPORT4A */
	E_SYS_SPU_PID_SPORT4B,									/* D_SYS_SPU_WP_SPORT4B */
	E_SYS_SPU_PID_SPORT5A,									/* D_SYS_SPU_WP_SPORT5A */
	E_SYS_SPU_PID_SPORT5B,									/* D_SYS_SPU_WP_SPORT5B */
	E_SYS_SPU_PID_SPORT6A,									/* D_SYS_SPU_WP_SPORT6A */
	E_SYS_SPU_PID_SPORT6B,									/* D_SYS_SPU_WP_SPORT6B */
	E_SYS_SPU_PID_SPORT7A,									/* D_SYS_SPU_WP_SPORT7A */
	E_SYS_SPU_PID_SPORT7B,									/* D_SYS_SPU_WP_SPORT7B */
	E_SYS_SPU_PID_UART0,									/* D_SYS_SPU_WP_UART0 */
	E_SYS_SPU_PID_WDG0,										/* D_SYS_SPU_WP_WDG0 */
	E_SYS_SPU_PID_SPORT0A_DMA0,								/* D_SYS_SPU_WP_SPORT0A_DMA0 */
	E_SYS_SPU_PID_SPORT0B_DMA1,								/* D_SYS_SPU_WP_SPORT0A_DMA1 */
	E_SYS_SPU_PID_SPORT1A_DMA2,								/* D_SYS_SPU_WP_SPORT1A_DMA2 */
	E_SYS_SPU_PID_SPORT4A_DMA10,							/* D_SYS_SPU_WP_SPORT4A_DMA10 */
	E_SYS_SPU_PID_SPORT4B_DMA11,							/* D_SYS_SPU_WP_SPORT4B_DMA11 */
	E_SYS_SPU_PID_SPORT5A_DMA12,							/* D_SYS_SPU_WP_SPORT5A_DMA12 */
	E_SYS_SPU_PID_SPORT5B_DMA13,							/* D_SYS_SPU_WP_SPORT5B_DMA13 */
	E_SYS_SPU_PID_SPORT6A_DMA14,							/* D_SYS_SPU_WP_SPORT6A_DMA14 */
	E_SYS_SPU_PID_SPORT6B_DMA15,							/* D_SYS_SPU_WP_SPORT6B_DMA15 */
	E_SYS_SPU_PID_SPORT7A_DMA16,							/* D_SYS_SPU_WP_SPORT7A_DMA16 */
	E_SYS_SPU_PID_SPORT7B_DMA17,							/* D_SYS_SPU_WP_SPORT7B_DMA17 */
	E_SYS_SPU_PID_UART0_RX_DMA20,							/* D_SYS_SPU_WP_UART0_RX_DMA20 */
	E_SYS_SPU_PID_UART0_TX_DMA21,							/* D_SYS_SPU_WP_UART0_TX_DMA21 */
	E_SYS_SPU_PID_MDMA0_SRC_DMA8,							/* D_SYS_SPU_WP_MDMA0_SRC_DMA8 */
	E_SYS_SPU_PID_MDMA0_DST_DMA9,							/* D_SYS_SPU_WP_MDMA0_DST_DMA9 */
	E_SYS_SPU_PID_MDMA1_SRC_DMA18,							/* D_SYS_SPU_WP_MDMA1_SRC_DMA18 */
	E_SYS_SPU_PID_MDMA1_DST_DMA19,							/* D_SYS_SPU_WP_MDMA1_DST_DMA19 */
	E_SYS_SPU_PID_SPI0,										/* D_SYS_SPU_WP_SPI0 */
	E_SYS_SPU_PID_SPI2,										/* D_SYS_SPU_WP_SPI2 */
	E_SYS_SPU_PID_MDMA2,									/* D_SYS_SPU_WP_MDMA2 */
	E_SYS_SPU_PID_MAX										/* Must add above this line! */
} E_SYS_SPU_PID;


uint32_t SYSTEM_SPU_Init(void);


#endif /* __SYSTEM_SPU_H__ */
