/*****************************************************************************
 * SYSTEM_SPU.h
 *****************************************************************************/

#ifndef __SYSTEM_SPU_H__
#define __SYSTEM_SPU_H__

#define D_SYS_SPU_WP_LP0 (3 /*Link Port 0*/)
#define D_SYS_SPU_WP_LP1 (4 /*Link Port 1*/)
#define D_SYS_SPU_WP_LP0_DMA30 (5 /*Link Port 0 DDE*/)
#define D_SYS_SPU_WP_LP1_DMA36 (6 /*Link Port 1 DDE*/)
#define D_SYS_SPU_WP_SPORT0A (13 /*Serial Port 0A*/)
#define D_SYS_SPU_WP_SPORT0B (14 /*Serial Port 0B*/)
#define D_SYS_SPU_WP_SPORT1A (15 /*Serial Port 1A*/)
#define D_SYS_SPU_WP_SPORT1B (16 /*Serial Port 1B*/)
#define D_SYS_SPU_WP_SPORT2A (17 /*Serial Port 2A*/)
#define D_SYS_SPU_WP_SPORT2B (18 /*Serial Port 2B*/)
#define D_SYS_SPU_WP_SPORT3A (19 /*Serial Port 3A*/)
#define D_SYS_SPU_WP_SPORT3B (20 /*Serial Port 3B*/)
#define D_SYS_SPU_WP_SPORT4A (21 /*Serial Port 4A*/)
#define D_SYS_SPU_WP_SPORT4B (22 /*Serial Port 4B*/)
#define D_SYS_SPU_WP_SPORT5A (23 /*Serial Port 5A*/)
#define D_SYS_SPU_WP_SPORT5B (24 /*Serial Port 5B*/)
#define D_SYS_SPU_WP_SPORT6A (25 /*Serial Port 6A*/)
#define D_SYS_SPU_WP_SPORT6B (26 /*Serial Port 6B*/)
#define D_SYS_SPU_WP_SPORT7A (27 /*Serial Port 7A*/)
#define D_SYS_SPU_WP_SPORT7B (28 /*Serial Port 7B*/)
#define D_SYS_SPU_WP_PORTA (32 /*General-Purpose Input/Output Port A*/)
#define D_SYS_SPU_WP_PORTB (33 /*General-Purpose Input/Output Port B*/)
#define D_SYS_SPU_WP_PORTC (34 /*General-Purpose Input/Output Port C*/)

/* Reserved */
#define D_SYS_SPU_WP_SPORT0A_DMA0 (49 /*SPORT0A DDE*/)
#define D_SYS_SPU_WP_SPORT0B_DMA1 (50 /*SPORT0B DDE*/)
#define D_SYS_SPU_WP_SPORT1A_DMA2 (51 /*SPORT1A DDE*/)
#define D_SYS_SPU_WP_SPORT1B_DMA3 (52 /*SPORT1B DDE*/)
#define D_SYS_SPU_WP_SPORT2A_DMA4 (53 /*SPORT2A DDE*/)
#define D_SYS_SPU_WP_SPORT2B_DMA5 (54 /*SPORT2B DDE*/)
#define D_SYS_SPU_WP_SPORT3A_DMA6 (55 /*SPORT3A DDE*/)
#define D_SYS_SPU_WP_SPORT3B_DMA7 (56 /*SPORT3B DDE*/)
#define D_SYS_SPU_WP_SPORT4A_DMA10 (57 /*SPORT4A DDE*/)
#define D_SYS_SPU_WP_SPORT4B_DMA11 (58 /*SPORT4B DDE*/)
#define D_SYS_SPU_WP_SPORT5A_DMA12 (59 /*SPORT5A DDE*/)
#define D_SYS_SPU_WP_SPORT5B_DMA13 (60 /*SPORT5B DDE*/)
#define D_SYS_SPU_WP_SPORT6A_DMA14 (61 /*SPORT6A DDE*/)
#define D_SYS_SPU_WP_SPORT6B_DMA15 (62 /*SPORT6B DDE*/)
#define D_SYS_SPU_WP_SPORT7A_DMA16 (63 /*SPORT7A DDE*/)
#define D_SYS_SPU_WP_SPORT7B_DMA17 (64 /*SPORT7B DDE*/)
#define D_SYS_SPU_WP_UART1_RX_DMA35 (67 /*UART1RX DDE*/)
#define D_SYS_SPU_WP_UART1_TX_DMA34 (68 /*UART1TX DDE*/)
#define D_SYS_SPU_WP_UART2_RX_DMA38 (69 /*UART2RX DDE*/)
#define D_SYS_SPU_WP_UART2_TX_DMA37 (70 /*UART2TX DDE*/)

/* 72 - reserved */
#define D_SYS_SPU_WP_SPI0 (79 /*Serial Peripheral Interface 0*/)
#define D_SYS_SPU_WP_SPI1 (80 /*Serial Peripheral Interface 1*/)
#define D_SYS_SPU_WP_SPI2 (81 /*Serial Peripheral Interface 2*/)

/* 84 - reserved */
#define D_SYS_SPU_WP_MDMA0_DDE0_DMA8 (110 /*MDMA0 DDE0 CRC0*/)
#define D_SYS_SPU_WP_MDMA0_DDE1_DMA9 (111 /*MDMA0 DDE1 CRC0*/)
#define D_SYS_SPU_WP_MDMA1_DDE0_DMA18 (112 /*MDMA1 DDE0 CRC1*/)
#define D_SYS_SPU_WP_MDMA1_DDE1_DMA19 (113 /*MDMA1 DDE1 CRC1*/)

typedef enum _E_SYS_SPU_PID_
{
	E_SYS_SPU_PID_SPORT0A				= 0,				/* D_SYS_SPU_WP_SPORT0A */
	E_SYS_SPU_PID_SPORT0B,									/* D_SYS_SPU_WP_SPORT0B */
	E_SYS_SPU_PID_SPORT1A,									/* D_SYS_SPU_WP_SPORT1A */
	E_SYS_SPU_PID_SPORT1B,									/* D_SYS_SPU_WP_SPORT1B */
	E_SYS_SPU_PID_SPORT2A,									/* D_SYS_SPU_WP_SPORT2A */
	E_SYS_SPU_PID_SPORT2B,									/* D_SYS_SPU_WP_SPORT2B */
	E_SYS_SPU_PID_SPORT3A,									/* D_SYS_SPU_WP_SPORT3A */
	E_SYS_SPU_PID_SPORT3B,									/* D_SYS_SPU_WP_SPORT3B */
	E_SYS_SPU_PID_SPORT4A,									/* D_SYS_SPU_WP_SPORT4A */
	E_SYS_SPU_PID_SPORT4B,									/* D_SYS_SPU_WP_SPORT4B */
	E_SYS_SPU_PID_SPORT5A,									/* D_SYS_SPU_WP_SPORT5A */
	E_SYS_SPU_PID_SPORT5B,									/* D_SYS_SPU_WP_SPORT5B */
	E_SYS_SPU_PID_SPORT6A,									/* D_SYS_SPU_WP_SPORT6A */
	E_SYS_SPU_PID_SPORT6B,									/* D_SYS_SPU_WP_SPORT6B */
	E_SYS_SPU_PID_SPORT7A,									/* D_SYS_SPU_WP_SPORT7A */
	E_SYS_SPU_PID_SPORT7B,									/* D_SYS_SPU_WP_SPORT7B */
	E_SYS_SPU_PID_LP0,    
   E_SYS_SPU_PID_LP1,
   E_SYS_SPU_PID_LP0_DMA30,
   E_SYS_SPU_PID_LP1_DMA36,
   E_SYS_SPU_PID_PORTA,
   E_SYS_SPU_PID_PORTB,
   E_SYS_SPU_PID_PORTC,    
	E_SYS_SPU_PID_SPORT0A_DMA0,								/* D_SYS_SPU_WP_SPORT0A_DMA0 */
	E_SYS_SPU_PID_SPORT0B_DMA1,								/* D_SYS_SPU_WP_SPORT0A_DMA1 */
	E_SYS_SPU_PID_SPORT1A_DMA2,								/* D_SYS_SPU_WP_SPORT1A_DMA2 */
	E_SYS_SPU_PID_SPORT1B_DMA3,								/* D_SYS_SPU_WP_SPORT1B_DMA3 */
	E_SYS_SPU_PID_SPORT2A_DMA4,								/* D_SYS_SPU_WP_SPORT2A_DMA4 */
	E_SYS_SPU_PID_SPORT2B_DMA5,								/* D_SYS_SPU_WP_SPORT2B_DMA5 */
	E_SYS_SPU_PID_SPORT3A_DMA6,								/* D_SYS_SPU_WP_SPORT3A_DMA6 */
	E_SYS_SPU_PID_SPORT3B_DMA7,								/* D_SYS_SPU_WP_SPORT3B_DMA7 */	
	E_SYS_SPU_PID_SPORT4A_DMA10,							/* D_SYS_SPU_WP_SPORT4A_DMA10 */
	E_SYS_SPU_PID_SPORT4B_DMA11,							/* D_SYS_SPU_WP_SPORT4B_DMA11 */
	E_SYS_SPU_PID_SPORT5A_DMA12,							/* D_SYS_SPU_WP_SPORT5A_DMA12 */
	E_SYS_SPU_PID_SPORT5B_DMA13,							/* D_SYS_SPU_WP_SPORT5B_DMA13 */
	E_SYS_SPU_PID_SPORT6A_DMA14,							/* D_SYS_SPU_WP_SPORT6A_DMA14 */
	E_SYS_SPU_PID_SPORT6B_DMA15,							/* D_SYS_SPU_WP_SPORT6B_DMA15 */
	E_SYS_SPU_PID_SPORT7A_DMA16,							/* D_SYS_SPU_WP_SPORT7A_DMA16 */
	E_SYS_SPU_PID_SPORT7B_DMA17,							/* D_SYS_SPU_WP_SPORT7B_DMA17 */
	E_SYS_SPU_PID_UART1_TX_DMA34,
   E_SYS_SPU_PID_UART1_RX_DMA35,
   E_SYS_SPU_PID_UART2_TX_DMA37,
   E_SYS_SPU_PID_UART2_RX_DMA38,

   E_SYS_SPU_PID_MDMA0_DDE0_DMA8, 
   E_SYS_SPU_PID_MDMA0_DDE1_DMA9,
   E_SYS_SPU_PID_MDMA1_DDE0_DMA18,
   E_SYS_SPU_PID_MDMA1_DDE1_DMA19,
   E_SYS_SPU_PID_SPI0,
   E_SYS_SPU_PID_SPI1,
   E_SYS_SPU_PID_SPI2,	
   E_SYS_SPU_PID_MAX										/* Must add above this line! */
} E_SYS_SPU_PID;


uint32_t SYSTEM_SPU_Init(void);


#endif /* __SYSTEM_SPU_H__ */
